import { db } from '@/db';
import { courses, modules, lessons, lessonMaterials, userEnrollments, userProgress } from '@/db/postgres-schema';
import { user, account } from '@/db/auth-schema';

async function main() {
    // Seed Users (Better Auth schema)
    const sampleUsers = [
        {
            id: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            email: 'marie.bakari@email.com',
            name: 'Marie Bakari',
            emailVerified: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            id: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            email: 'jean.mukendi@email.com',
            name: 'Jean Mukendi',
            emailVerified: true,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            id: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            email: 'grace.nzuzi@email.com',
            name: 'Grace Nzuzi',
            emailVerified: true,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            id: 'user_01h4kxt2e8z9y3b1n7m6q5w8r7',
            email: 'paul.tshisekedi@email.com',
            name: 'Paul Tshisekedi',
            emailVerified: true,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            id: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            email: 'sarah.kabongo@email.com',
            name: 'Sarah Kabongo',
            emailVerified: true,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
    ];

    await db.insert(user).values(sampleUsers);

    // Seed Accounts (Better Auth credential provider)
    const sampleAccounts = [
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            accountId: 'marie.bakari@email.com',
            providerId: 'credential',
            password: '$2a$10$somehashedpassword1',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            accountId: 'jean.mukendi@email.com',
            providerId: 'credential',
            password: '$2a$10$somehashedpassword2',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            accountId: 'grace.nzuzi@email.com',
            providerId: 'credential',
            password: '$2a$10$somehashedpassword3',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r7',
            accountId: 'paul.tshisekedi@email.com',
            providerId: 'credential',
            password: '$2a$10$somehashedpassword4',
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            accountId: 'sarah.kabongo@email.com',
            providerId: 'credential',
            password: '$2a$10$somehashedpassword5',
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
    ];

    await db.insert(account).values(sampleAccounts);

    // Seed Courses
    const sampleCourses = [
        {
            title: 'Lingala for Beginners',
            description: 'Start your journey learning Lingala from scratch. Perfect for absolute beginners wanting to learn basic greetings, numbers, and everyday conversation.',
            level: 'beginner',
            language: 'lingala',
            thumbnailUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353',
            price: 29.99,
            isPublished: 1,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            title: 'Intermediate Lingala Conversation',
            description: 'Build on your basics and engage in real-world conversations. Learn practical phrases for shopping, travel, and social interactions.',
            level: 'intermediate',
            language: 'lingala',
            thumbnailUrl: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f',
            price: 49.99,
            isPublished: 1,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            title: 'Advanced Lingala Grammar',
            description: 'Master complex grammar structures, idiomatic expressions, and explore Lingala literature. For serious learners wanting fluency.',
            level: 'advanced',
            language: 'lingala',
            thumbnailUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8',
            price: 69.99,
            isPublished: 1,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
    ];

    await db.insert(courses).values(sampleCourses);

    // Seed Modules
    const sampleModules = [
        {
            courseId: 1,
            title: 'Basic Greetings',
            description: 'Learn essential greetings and introductions in Lingala',
            orderIndex: 1,
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            courseId: 1,
            title: 'Numbers and Time',
            description: 'Master counting and telling time in Lingala',
            orderIndex: 2,
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            courseId: 1,
            title: 'Family and Relationships',
            description: 'Vocabulary for family members and social relationships',
            orderIndex: 3,
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            courseId: 2,
            title: 'Shopping and Markets',
            description: 'Navigate markets and shops with confidence',
            orderIndex: 1,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            courseId: 2,
            title: 'Travel and Directions',
            description: 'Get around town and ask for directions',
            orderIndex: 2,
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            courseId: 3,
            title: 'Complex Verb Tenses',
            description: 'Master past, present, future, and conditional tenses',
            orderIndex: 1,
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            courseId: 3,
            title: 'Idiomatic Expressions',
            description: 'Learn common sayings and cultural expressions',
            orderIndex: 2,
            createdAt: new Date('2024-01-21').toISOString(),
        },
        {
            courseId: 3,
            title: 'Lingala Literature',
            description: 'Explore poetry, prose, and traditional storytelling',
            orderIndex: 3,
            createdAt: new Date('2024-01-21').toISOString(),
        },
    ];

    await db.insert(modules).values(sampleModules);

    // Seed Lessons
    const sampleLessons = [
        // Module 1: Basic Greetings (3 lessons)
        {
            moduleId: 1,
            title: 'Hello and Goodbye',
            content: 'Learn the most common greetings: Mbote (Hello), Tika malamu (Goodbye), and when to use them.',
            videoUrl: 'https://www.youtube.com/watch?v=sample1',
            orderIndex: 1,
            durationMinutes: 15,
            freePreview: 1,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            moduleId: 1,
            title: 'Introducing Yourself',
            content: 'Practice introducing yourself: Kombo na ngai ezali... (My name is...)',
            videoUrl: 'https://www.youtube.com/watch?v=sample2',
            orderIndex: 2,
            durationMinutes: 20,
            freePreview: 0,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            moduleId: 1,
            title: 'Formal vs Informal Greetings',
            content: 'Understand the difference between formal and casual greetings in different contexts.',
            videoUrl: 'https://www.youtube.com/watch?v=sample3',
            orderIndex: 3,
            durationMinutes: 18,
            freePreview: 0,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        // Module 2: Numbers and Time (3 lessons)
        {
            moduleId: 2,
            title: 'Counting 1-100',
            content: 'Master numbers from moko (one) to nkama moko (one hundred).',
            videoUrl: 'https://www.youtube.com/watch?v=sample4',
            orderIndex: 1,
            durationMinutes: 25,
            freePreview: 0,
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            moduleId: 2,
            title: 'Telling Time',
            content: 'Learn to ask and tell time: Ngonga boni? (What time is it?)',
            videoUrl: 'https://www.youtube.com/watch?v=sample5',
            orderIndex: 2,
            durationMinutes: 22,
            freePreview: 0,
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            moduleId: 2,
            title: 'Days and Months',
            content: 'Vocabulary for days of the week and months of the year.',
            videoUrl: 'https://www.youtube.com/watch?v=sample6',
            orderIndex: 3,
            durationMinutes: 20,
            freePreview: 0,
            createdAt: new Date('2024-01-13').toISOString(),
        },
        // Module 3: Family (3 lessons)
        {
            moduleId: 3,
            title: 'Immediate Family',
            content: 'Learn words for mother (mama), father (tata), and siblings.',
            videoUrl: 'https://www.youtube.com/watch?v=sample7',
            orderIndex: 1,
            durationMinutes: 18,
            freePreview: 0,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            moduleId: 3,
            title: 'Extended Family',
            content: 'Vocabulary for aunts, uncles, cousins, and grandparents.',
            videoUrl: 'https://www.youtube.com/watch?v=sample8',
            orderIndex: 2,
            durationMinutes: 20,
            freePreview: 0,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            moduleId: 3,
            title: 'Describing Relationships',
            content: 'Talk about your family and relationships using descriptive phrases.',
            videoUrl: 'https://www.youtube.com/watch?v=sample9',
            orderIndex: 3,
            durationMinutes: 22,
            freePreview: 0,
            createdAt: new Date('2024-01-14').toISOString(),
        },
        // Module 4: Shopping (4 lessons)
        {
            moduleId: 4,
            title: 'At the Market',
            content: 'Essential vocabulary for shopping at traditional markets.',
            videoUrl: 'https://www.youtube.com/watch?v=sample10',
            orderIndex: 1,
            durationMinutes: 25,
            freePreview: 1,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            moduleId: 4,
            title: 'Bargaining and Prices',
            content: 'Learn to negotiate prices: Mbongo boni? (How much?)',
            videoUrl: 'https://www.youtube.com/watch?v=sample11',
            orderIndex: 2,
            durationMinutes: 23,
            freePreview: 0,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            moduleId: 4,
            title: 'Food and Groceries',
            content: 'Vocabulary for common foods and how to order them.',
            videoUrl: 'https://www.youtube.com/watch?v=sample12',
            orderIndex: 3,
            durationMinutes: 28,
            freePreview: 0,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            moduleId: 4,
            title: 'Payment Methods',
            content: 'Discussing payment: cash, mobile money, and receipts.',
            videoUrl: 'https://www.youtube.com/watch?v=sample13',
            orderIndex: 4,
            durationMinutes: 20,
            freePreview: 0,
            createdAt: new Date('2024-01-17').toISOString(),
        },
        // Module 5: Travel (3 lessons)
        {
            moduleId: 5,
            title: 'Asking for Directions',
            content: 'How to ask: Wapi na kende...? (Where do I go to...?)',
            videoUrl: 'https://www.youtube.com/watch?v=sample14',
            orderIndex: 1,
            durationMinutes: 22,
            freePreview: 0,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            moduleId: 5,
            title: 'Transportation',
            content: 'Vocabulary for taxis, buses, and walking directions.',
            videoUrl: 'https://www.youtube.com/watch?v=sample15',
            orderIndex: 2,
            durationMinutes: 24,
            freePreview: 0,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            moduleId: 5,
            title: 'Landmarks and Locations',
            content: 'Common places: hospital, school, church, market, etc.',
            videoUrl: 'https://www.youtube.com/watch?v=sample16',
            orderIndex: 3,
            durationMinutes: 26,
            freePreview: 0,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        // Module 6: Complex Verbs (3 lessons)
        {
            moduleId: 6,
            title: 'Past Tense Mastery',
            content: 'Form and use past tense verbs correctly in various contexts.',
            videoUrl: 'https://www.youtube.com/watch?v=sample17',
            orderIndex: 1,
            durationMinutes: 30,
            freePreview: 1,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            moduleId: 6,
            title: 'Future and Conditional',
            content: 'Express future plans and hypothetical situations.',
            videoUrl: 'https://www.youtube.com/watch?v=sample18',
            orderIndex: 2,
            durationMinutes: 28,
            freePreview: 0,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            moduleId: 6,
            title: 'Subjunctive Mood',
            content: 'Advanced grammar: expressing wishes, doubts, and emotions.',
            videoUrl: 'https://www.youtube.com/watch?v=sample19',
            orderIndex: 3,
            durationMinutes: 32,
            freePreview: 0,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        // Module 7: Idioms (3 lessons)
        {
            moduleId: 7,
            title: 'Common Proverbs',
            content: 'Learn traditional Lingala proverbs and their meanings.',
            videoUrl: 'https://www.youtube.com/watch?v=sample20',
            orderIndex: 1,
            durationMinutes: 25,
            freePreview: 0,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            moduleId: 7,
            title: 'Everyday Expressions',
            content: 'Idiomatic phrases used in daily conversation.',
            videoUrl: 'https://www.youtube.com/watch?v=sample21',
            orderIndex: 2,
            durationMinutes: 27,
            freePreview: 0,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            moduleId: 7,
            title: 'Cultural Context',
            content: 'Understanding the cultural background of common expressions.',
            videoUrl: 'https://www.youtube.com/watch?v=sample22',
            orderIndex: 3,
            durationMinutes: 29,
            freePreview: 0,
            createdAt: new Date('2024-01-23').toISOString(),
        },
        // Module 8: Literature (3 lessons)
        {
            moduleId: 8,
            title: 'Lingala Poetry',
            content: 'Explore classic and contemporary Lingala poetry.',
            videoUrl: 'https://www.youtube.com/watch?v=sample23',
            orderIndex: 1,
            durationMinutes: 30,
            freePreview: 0,
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            moduleId: 8,
            title: 'Storytelling Traditions',
            content: 'Learn about oral storytelling and folktales.',
            videoUrl: 'https://www.youtube.com/watch?v=sample24',
            orderIndex: 2,
            durationMinutes: 28,
            freePreview: 0,
            createdAt: new Date('2024-01-24').toISOString(),
        },
        {
            moduleId: 8,
            title: 'Modern Lingala Writing',
            content: 'Contemporary literature and written expression.',
            videoUrl: 'https://www.youtube.com/watch?v=sample25',
            orderIndex: 3,
            durationMinutes: 26,
            freePreview: 0,
            createdAt: new Date('2024-01-24').toISOString(),
        },
    ];

    await db.insert(lessons).values(sampleLessons);

    // Seed Lesson Materials
    const sampleMaterials = [
        {
            lessonId: 1,
            title: 'Greetings Vocabulary Guide',
            type: 'pdf',
            url: 'https://example.com/materials/greetings-guide.pdf',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            lessonId: 1,
            title: 'Pronunciation Practice Audio',
            type: 'audio',
            url: 'https://example.com/materials/greetings-audio.mp3',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            lessonId: 2,
            title: 'Introduction Practice Quiz',
            type: 'quiz',
            url: 'https://example.com/materials/intro-quiz',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            lessonId: 4,
            title: 'Numbers 1-100 Chart',
            type: 'pdf',
            url: 'https://example.com/materials/numbers-chart.pdf',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            lessonId: 4,
            title: 'Counting Practice Audio',
            type: 'audio',
            url: 'https://example.com/materials/counting-audio.mp3',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            lessonId: 5,
            title: 'Time Telling Examples',
            type: 'video',
            url: 'https://www.youtube.com/watch?v=time-examples',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            lessonId: 7,
            title: 'Family Tree Worksheet',
            type: 'pdf',
            url: 'https://example.com/materials/family-worksheet.pdf',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            lessonId: 10,
            title: 'Market Vocabulary List',
            type: 'pdf',
            url: 'https://example.com/materials/market-vocab.pdf',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            lessonId: 11,
            title: 'Bargaining Role-Play Audio',
            type: 'audio',
            url: 'https://example.com/materials/bargaining-audio.mp3',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            lessonId: 12,
            title: 'Food Vocabulary Quiz',
            type: 'quiz',
            url: 'https://example.com/materials/food-quiz',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            lessonId: 14,
            title: 'Directions Practice Scenarios',
            type: 'pdf',
            url: 'https://example.com/materials/directions-scenarios.pdf',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            lessonId: 17,
            title: 'Past Tense Exercise Workbook',
            type: 'pdf',
            url: 'https://example.com/materials/past-tense-workbook.pdf',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            lessonId: 18,
            title: 'Future Tense Video Examples',
            type: 'video',
            url: 'https://www.youtube.com/watch?v=future-tense',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            lessonId: 20,
            title: 'Proverbs Collection PDF',
            type: 'pdf',
            url: 'https://example.com/materials/proverbs.pdf',
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            lessonId: 23,
            title: 'Poetry Anthology',
            type: 'pdf',
            url: 'https://example.com/materials/poetry-anthology.pdf',
            createdAt: new Date('2024-01-24').toISOString(),
        },
    ];

    await db.insert(lessonMaterials).values(sampleMaterials);

    // Seed User Enrollments
    const sampleEnrollments = [
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            courseId: 1,
            enrolledAt: new Date('2024-01-20').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            courseId: 2,
            enrolledAt: new Date('2024-02-10').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            courseId: 1,
            enrolledAt: new Date('2024-02-05').toISOString(),
            completedAt: new Date('2024-03-15').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            courseId: 2,
            enrolledAt: new Date('2024-03-16').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            courseId: 1,
            enrolledAt: new Date('2024-02-20').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            courseId: 3,
            enrolledAt: new Date('2024-03-01').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r7',
            courseId: 2,
            enrolledAt: new Date('2024-03-10').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            courseId: 1,
            enrolledAt: new Date('2024-03-20').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            courseId: 2,
            enrolledAt: new Date('2024-03-25').toISOString(),
            completedAt: null,
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            courseId: 3,
            enrolledAt: new Date('2024-03-28').toISOString(),
            completedAt: null,
        },
    ];

    await db.insert(userEnrollments).values(sampleEnrollments);

    // Seed User Progress
    const sampleProgress = [
        // Marie's progress (Course 1)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            lessonId: 1,
            completed: 1,
            completedAt: new Date('2024-01-21').toISOString(),
            lastPositionSeconds: 900,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            lessonId: 2,
            completed: 1,
            completedAt: new Date('2024-01-23').toISOString(),
            lastPositionSeconds: 1200,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            lessonId: 3,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 450,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        // Jean's progress (Course 1 completed)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            lessonId: 1,
            completed: 1,
            completedAt: new Date('2024-02-06').toISOString(),
            lastPositionSeconds: 900,
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            lessonId: 2,
            completed: 1,
            completedAt: new Date('2024-02-08').toISOString(),
            lastPositionSeconds: 1200,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            lessonId: 3,
            completed: 1,
            completedAt: new Date('2024-02-10').toISOString(),
            lastPositionSeconds: 1080,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            lessonId: 4,
            completed: 1,
            completedAt: new Date('2024-02-15').toISOString(),
            lastPositionSeconds: 1500,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        // Jean's progress in Course 2
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            lessonId: 10,
            completed: 1,
            completedAt: new Date('2024-03-18').toISOString(),
            lastPositionSeconds: 1500,
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r5',
            lessonId: 11,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 780,
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        // Grace's progress (Course 1)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 1,
            completed: 1,
            completedAt: new Date('2024-02-22').toISOString(),
            lastPositionSeconds: 900,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 2,
            completed: 1,
            completedAt: new Date('2024-02-24').toISOString(),
            lastPositionSeconds: 1200,
            createdAt: new Date('2024-02-24').toISOString(),
            updatedAt: new Date('2024-02-24').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 3,
            completed: 1,
            completedAt: new Date('2024-02-26').toISOString(),
            lastPositionSeconds: 1080,
            createdAt: new Date('2024-02-26').toISOString(),
            updatedAt: new Date('2024-02-26').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 4,
            completed: 1,
            completedAt: new Date('2024-02-28').toISOString(),
            lastPositionSeconds: 1500,
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 5,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 660,
            createdAt: new Date('2024-03-02').toISOString(),
            updatedAt: new Date('2024-03-02').toISOString(),
        },
        // Grace's progress (Course 3)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 17,
            completed: 1,
            completedAt: new Date('2024-03-05').toISOString(),
            lastPositionSeconds: 1800,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r6',
            lessonId: 18,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 920,
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        // Paul's progress (Course 2)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r7',
            lessonId: 10,
            completed: 1,
            completedAt: new Date('2024-03-12').toISOString(),
            lastPositionSeconds: 1500,
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r7',
            lessonId: 11,
            completed: 1,
            completedAt: new Date('2024-03-14').toISOString(),
            lastPositionSeconds: 1380,
            createdAt: new Date('2024-03-14').toISOString(),
            updatedAt: new Date('2024-03-14').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r7',
            lessonId: 12,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 480,
            createdAt: new Date('2024-03-16').toISOString(),
            updatedAt: new Date('2024-03-16').toISOString(),
        },
        // Sarah's progress (Course 1)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            lessonId: 1,
            completed: 1,
            completedAt: new Date('2024-03-21').toISOString(),
            lastPositionSeconds: 900,
            createdAt: new Date('2024-03-21').toISOString(),
            updatedAt: new Date('2024-03-21').toISOString(),
        },
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            lessonId: 2,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 340,
            createdAt: new Date('2024-03-23').toISOString(),
            updatedAt: new Date('2024-03-23').toISOString(),
        },
        // Sarah's progress (Course 2)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            lessonId: 10,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 120,
            createdAt: new Date('2024-03-26').toISOString(),
            updatedAt: new Date('2024-03-26').toISOString(),
        },
        // Sarah's progress (Course 3)
        {
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r8',
            lessonId: 17,
            completed: 0,
            completedAt: null,
            lastPositionSeconds: 240,
            createdAt: new Date('2024-03-29').toISOString(),
            updatedAt: new Date('2024-03-29').toISOString(),
        },
    ];

    await db.insert(userProgress).values(sampleProgress);

    console.log('✅ Seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});